# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 34f7875aaf2fdf00069b5a02532f0e5f5ca30931f23084ffedfaf9f07813a73feb672886f6fb66604e7380b9ce11909da3e0bfae913bb8ec3bc1e6bf7f10fd64

test:
  secret_key_base: 82faa785a10e73565cdadfe677b5ad6d853e11920ea5c6be573b8659950102d76c9284f65b232879eaf969f374704d81fdf00d4c104bd4604db282beed99527b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
